### ISSUE TITLE
安卓上报错content-length接收的和发送的不一样

### ISSUE THREAD

**Issue by RichileLiu** [TencentCloud/tencentcloud-cls-sdk-java#10]
同样的代码，在电脑上就没问题，log如下：

电脑上的log和安卓上的log一样的，但是就是结果不一样

System.out: Header: Host: ap-guangzhou.cls.tencentcs.com
System.out: Header: Content-Length: 255
System.out: Header: x-cls-compress-type: lz4
System.out: Header: cls-java-sdk-version: 1.0.12
System.out: Header: Content-Type: application/x-protobuf
System.out: length: 160
System.out: The batch handler has been interrupted
System.out: Result{successful=false, reservedAttempts=[Attempt{success=false, requestId='null', errorCode='SendFailed', errorMessage='content-length promised 255 bytes, but received 160', timestampMs=1667130612170}], attemptCount=1}

**Comment by RichileLiu** [comment]
若把SendProducerBatchTask.sendLogs中的headParameter.put("x-cls-compress-type", "lz4");去掉，并且把compressedData改为body，则就可以成功。请问cls还支持除了lz4压缩算法以外的压缩吗？

**Comment by farmerx** [comment]
用android sdk
