### ISSUE TITLE
slf4j冲突

### ISSUE THREAD

**Issue by TakahashiAmaki** [TencentCloud/tencentcloud-cls-sdk-java#7]
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/home/ubuntu/.gradle/caches/modules-2/files-2.1/com.tencentcloudapi.cls/tencentcloud-cls-sdk-java/1.0.9/3c6e7cb01cea831609bd0f258025a64e2abf9fb0/tencentcloud-cls-sdk-java-1.0.9.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/home/ubuntu/.gradle/caches/modules-2/files-2.1/ch.qos.logback/logback-classic/1.2.10/f69d97ef3335c6ab82fc21dfb77ac613f90c1221/logback-classic-1.2.10.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [ch.qos.logback.classic.util.ContextSelectorStaticBinder]

**Comment by farmerx** [comment]
使用1.0.10版本
